In [4]:
import os
import json
import pandas as pd

In [39]:
results_msol = None #todo
with open(os.path.join("results", "250131_1458", "classify_fol.json"), "r") as f:
    results_fol = pd.read_json(f)
with open(os.path.join("results", "250130_1000", "classify.json"), "r") as f:
    results_py = pd.read_json(f)

In [40]:
comp_df = results_fol.merge(results_py, on="chebi_id", suffixes=("_fol", "_py"))
comp_df

,chebi_id,charge_category_fol,n_amino_acid_residues_fol,functional_groups,proteinogenics_fol,time_fol,chebi_classes_fol,"2,5-diketopiperazines_fol",emericellamide_fol,charge_category_py,...,proteinogenics_locations,proteinogenics_locations_no_carboxy,carboxy_residue,amino_residue,chunks,longest_aa_chain,"2,5-diketopiperazines_py","2,5-diketopiperazines_atoms",emericellamide_py,emericellamide_atoms
0,15429,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0095,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30236,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0015,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15571,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0021,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16830,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [[0]], 'ca...",[],0.0018,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17790,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0014,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,27984,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0587,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39996,77188,NEUTRAL,1,"{'amide_bond': [[33, 34, 10]], 'amino_residue'...",[],0.0583,[],NaN,NaN,NEUTRAL,...,[],[],"[[33, 34, 10]]",[10],"[[0, 1, 3, 4, 5, 9], [12, 13, 14, 16, 17, 21],...",[],NaN,NaN,NaN,NaN
39997,147844,NEUTRAL,1,"{'amide_bond': [], 'amino_residue': [], 'carbo...",[],0.0231,[],NaN,NaN,NEUTRAL,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39998,16544,NEUTRAL,1,"{'amide_bond': [[2, 3, 6], [4, 5, 7], [28, 27,...",[],0.0386,[],NaN,NaN,NEUTRAL,...,[],[],"[[2, 3, 6], [4, 5, 7], [28, 27, 26]]","[6, 7, 26]","[[0, 1, 2], [8, 10, 12, 14, 15], [41, 19, 21, ...",[],NaN,NaN,NaN,NaN
39999,52892,CATION,1,"{'amide_bond': [], 'amino_residue': [[17], [27...",[],0.2336,[25697],NaN,NaN,CATION,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
comp_df[comp_df["charge_category_fol"] != comp_df["charge_category_py"]]

Empty DataFrame
Columns: [chebi_id, charge_category_fol, n_amino_acid_residues_fol, functional_groups, proteinogenics_fol, time_fol, chebi_classes_fol, 2,5-diketopiperazines_fol, emericellamide_fol, charge_category_py, n_amino_acid_residues_py, proteinogenics_py, time_py, chebi_classes_py, amide_bond, proteinogenics_locations, proteinogenics_locations_no_carboxy, carboxy_residue, amino_residue, chunks, longest_aa_chain, 2,5-diketopiperazines_py, 2,5-diketopiperazines_atoms, emericellamide_py, emericellamide_atoms]
Index: []

[0 rows x 25 columns]

In [42]:
comp_df[((comp_df["n_amino_acid_residues_fol"] >= 2) | (comp_df["n_amino_acid_residues_py"] >= 2)) & (comp_df["n_amino_acid_residues_fol"] != comp_df["n_amino_acid_residues_py"])]

Empty DataFrame
Columns: [chebi_id, charge_category_fol, n_amino_acid_residues_fol, functional_groups, proteinogenics_fol, time_fol, chebi_classes_fol, 2,5-diketopiperazines_fol, emericellamide_fol, charge_category_py, n_amino_acid_residues_py, proteinogenics_py, time_py, chebi_classes_py, amide_bond, proteinogenics_locations, proteinogenics_locations_no_carboxy, carboxy_residue, amino_residue, chunks, longest_aa_chain, 2,5-diketopiperazines_py, 2,5-diketopiperazines_atoms, emericellamide_py, emericellamide_atoms]
Index: []

[0 rows x 25 columns]

In [43]:
comp_df[(comp_df["n_amino_acid_residues_fol"] > 1) & pd.Series([any([aa not in row["proteinogenics_fol"] for aa in row["proteinogenics_py"]]) or any(aa not in row["proteinogenics_py"] for aa in row["proteinogenics_fol"]) for _, row in comp_df.iterrows()])][["chebi_id", "proteinogenics_fol", "proteinogenics_py"]]

       chebi_id  proteinogenics_fol   proteinogenics_py
29198     53490     [L, M, fMet, F]        [fMet, L, F]
30599    194314     [L, M, fMet, F]        [fMet, L, F]
39859     66742  [P, A, I, D, M, F]  [I, F, A, P, D, A]

In [13]:
comp_df[["time_fol", "time_py"]].describe()

           time_fol       time_py
count  76000.000000  76000.000000
mean       0.041726      0.000202
std        0.035455      0.000398
min        0.009700      0.000000
25%        0.024700      0.000100
50%        0.032200      0.000200
75%        0.042800      0.000200
max        0.463900      0.070300